#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"metadata": {"name": "controller-manager"}, "kind": "Deployment"})
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      imagePullSecrets:
      - name: tbs-install-pull-secret
      #@overlay/match missing_ok=True
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
      #@overlay/match by="name"
      - name: manager
      #@overlay/match missing_ok=True
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 200Mi
