#@ load("/values.star", "pull_secret_export", "tbs_source_docker_configjson")
---
apiVersion: v1
kind: Secret
metadata:
  name:  tbs-install-pull-secret
  namespace: stacks-operator-system
#@ if pull_secret_export:
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
#@ end
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ tbs_source_docker_configjson
