#@data/values-schema
---
kp_default_repository: ""
kp_default_repository_username: ""
kp_default_repository_password: ""

pull_from_kp_default_repo: false
pull_from_tanzunet: false
pull_secret_export: false

tbs_source_registry: ""
tbs_source_registry_username: ""
tbs_source_registry_password: ""

admin_users: ""
admin_groups: ""

ca_cert_data: ""

http_proxy: ""
https_proxy: ""
no_proxy: ""

disable_smart_warmer: false

tanzunet_username: ""
tanzunet_password: ""
descriptor_name: ""
descriptor_version: 100.0.241
enable_automatic_dependency_updates: false