#@ load("/values.star", "values")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  kp-config
  namespace: kpack
data:
  default.repository: #@ values.kp_default_repository
  default.repository.serviceaccount: kp-default-repository-serviceaccount
  canonical.repository: #@ values.kp_default_repository
  canonical.repository.serviceaccount: kp-default-repository-serviceaccount
