---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kp-default-repository-serviceaccount
  namespace:  kpack
imagePullSecrets:
- name: kp-default-repository-secret
secrets:
- name: kp-default-repository-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: canonical-registry-serviceaccount
  namespace:  kpack
imagePullSecrets:
- name: kp-default-repository-secret
secrets:
- name: kp-default-repository-secret