#@ load("/values.star", "pull_secret_export", "kp_default_docker_configjson", "kpack_source_docker_configjson")
---
apiVersion: v1
kind: Secret
metadata:
  name: kp-default-repository-secret
  namespace: kpack
  annotations:
    kapp.k14s.io/versioned: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ kp_default_docker_configjson

---
apiVersion: v1
kind: Secret
metadata:
  name: kpack-install-pull-secret
  namespace: kpack
  #@ if pull_secret_export:
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
#@ end
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ kpack_source_docker_configjson

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-pull-lifecycle-serviceaccount
  namespace: kpack
imagePullSecrets:
- name: kpack-install-pull-secret