#@ load("/values.star", "pull_secret_export", "cert_injection_webhook_source_docker_configjson")

---
apiVersion: v1
kind: Secret
metadata:
  name: cert-injection-webhook-install-pull-secret
  namespace: cert-injection-webhook
  #@ if pull_secret_export:
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
#@ end
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ cert_injection_webhook_source_docker_configjson