#@ load("/values.star", "pull_secret_export", "kp_default_docker_configjson", "tbs_source_docker_configjson")

apiVersion: v1
kind: Secret
metadata:
  name:  kp-default-repository-secret
  namespace: build-service
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ kp_default_docker_configjson

---
apiVersion: v1
kind: Secret
metadata:
  name:  tbs-install-pull-secret
  namespace: build-service
#@ if pull_secret_export:
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
#@ end
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ tbs_source_docker_configjson
